@startuml
'Compile with plantUML Online Server https://www.plantuml.com/plantuml/uml
allow_mixing

'RLFP

package "System" {
package "Requirements" {
  class BasicSafety <<requirement>>
  class EssentialPerformance <<requirement>>
  class LeakageCurrentLimit <<requirement>>
  class ControlRisk1 <<requirement>>
  class ControlRisk2 <<requirement>>
}

package "Logical Architecture" {

}

package "Functional Architecture" {

}

package "Physical Architecture" {

}

package "Use Cases" {
'Intended user profiles per IEC 62366-1
  actor HealthcareProfessionals
  actor Technician
  actor Patient
  actor LayPerson

  usecase "Run Self-Test" as UC1
  usecase "Log Failure" as UC2
  HealthcareProfessionals --> UC1
  Technician --> UC1
  HealthcareProfessionals --> UC2
  Technician --> UC2
  
  package "Primary operating functions" {
   usecase "Display Alarm" as UC3
   usecase "Monitor Patient" as UC4
   HealthcareProfessionals --> UC3
   HealthcareProfessionals --> UC4
  }
  
  package "Abnormal use" {
  usecase "AN use case 1" as UC5
  HealthcareProfessionals --> UC5
  }
  package "Hazard-related use scenarios" {
  usecase "HR use case 1" as UC6
  HealthcareProfessionals --> UC6
  }

}

}
@enduml